##
# Controller auto-generated by Typus.
# Use it to extend the admin functionality.
##
class Admin::AssetsController < AdminController

=begin

  ##
  # You can overwrite any of the AdminController methods.
  #
  def index
  end

  ##
  # You can extend the AdminController with your actions.
  #
  # This actions have to be defined in `typus.yml`.
  #
  #   Post:
  #     actions:
  #       list: action_for_the_listing
  #       form: action_for_the_form
  #
  def your_action
  end

=end

end

