source 'http://rubygems.org'

gem "rails", "~> 3.1.0.rc4"
gem "kaminari"
gem "jquery-rails"

gem "sqlite3"
gem "jquery-rails"
gem "ckeditor-rails", "0.0.2"
gem "sqlite3"

# And this stuff needed for the demo application.
gem "acts_as_list"
gem "acts_as_tree"
gem "factory_girl"
gem "rails-trash", "~> 1.1.1"

# Asset Management with Dragonfly
gem "dragonfly", "~> 0.9"
gem "rack-cache", :require => "rack/cache"

# Asset Management with Paperclip

gem "paperclip"

group :test do
  gem "shoulda-context"
  gem "mocha" # Make sure mocha is loaded at the end ...
end
