source 'http://rubygems.org'

gem "acts_as_list"
gem "acts_as_tree"
gem "capybara"
gem "factory_girl"
gem "fastercsv", "1.5.3"
gem "leftright"
gem "mocha"
gem "mysql"
gem "paperclip"
gem "pg"
gem "rails", "3.0.0"
gem "shoulda"
gem "sqlite3-ruby"
