# Controller generated by Typus, use it to extend admin functionality.
class Admin::<%= resource %>Controller < <%= inherits_from %>

  <%- if inherits_from.eql?("Admin::ServiceController") -%>
  def index
  end
  <%- end -%>

end
