require "test_helper"

# ControllerTest generated by Typus, use it to test the extended admin functionality.
class Admin::<%= resource %>ControllerTest < ActionController::TestCase

  # Replace this with your real tests.
  test "should redirect to sign in when user is not logged" do
    get :index
    assert_response :redirect
  end

end
