require "test_helper"

# ControllerTest generated by Typus, use it to test the extended admin functionality.
class Admin::<%= resource %>ControllerTest < ActionController::TestCase

  # Replace this with your real tests.
  test "render index" do
    get :index
    assert_response :success
    assert_template "index"
  end

end
