=begin
Typus::Configuration.options[:app_name] = "Typus"
Typus::Configuration.options[:app_description] = ""
Typus::Configuration.options[:per_page] = 15
Typus::Configuration.options[:form_rows] = 10
Typus::Configuration.options[:form_columns] = 10
Typus::Configuration.options[:minute_step] = 5
Typus::Configuration.options[:email] = 'admin@application.tld'
=end
