#!/usr/bin/env bash

SERVER=fesplugas@labs.francescesplugas.com
DEPLOY_TO=/home/fesplugas/public_html/typus-demo

echo "Pulling latest changes ..."
ssh $SERVER "cd $DEPLOY_TO && git pull"

echo "Removing Gemfile.lock ..."
ssh $SERVER "cd $DEPLOY_TO && rm Gemfile.lock"

echo "Running bundler ..."
ssh $SERVER "cd $DEPLOY_TO && bundle install"

echo "Restarting the application ..."
ssh $SERVER "cd $DEPLOY_TO && touch test/dummy/tmp/restart.txt"
